import { createServer } from 'vite'
import react from '@vitejs/plugin-react'
import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
const root = process.cwd(), output = path.join(root, '.task/myagent-settings-review')
await fs.mkdir(output, { recursive: true })
const server = await createServer({ root, configFile: false, plugins: [react()], optimizeDeps: { entries: ['tools/myagent-settings-review/index.html'] }, server: { host: '127.0.0.1', port: 5190 }, logLevel: 'error' })
await server.listen()
const browser = await chromium.launch({ headless: true }), page = await browser.newPage({ viewport: { width: 1000, height: 900 } }), errors = []
page.on('pageerror', e => errors.push(e.message))
const check = (name, ok) => { assert.ok(ok, name); console.log('PASS ' + name) }
try {
  await page.goto(server.resolvedUrls.local[0] + 'tools/myagent-settings-review/', { timeout: 60000 })
  await page.getByRole('textbox', { name: 'MyAgent chat model', exact: true }).waitFor()
  await page.getByRole('button', { name: 'Refresh status', exact: true }).waitFor({ state: 'visible' })
  check('readiness is probed only on demand', await page.evaluate(() => window.myAgentFixture.readinessChecks === 0))
  await page.getByRole('button', { name: 'Check readiness', exact: true }).click()
  await page.getByRole('status').filter({ hasText: 'Chat model starts on demand' }).waitFor()
  check('readiness distinguishes on-demand models and missing extraction dependencies', await page.getByText('LibreOffice is not installed.', { exact: true }).isVisible())
  check('diagnostics do not start a model', await page.evaluate(() => window.myAgentFixture.models.length === 0))
  await page.screenshot({ path: path.join(output, 'myagent-wide.png') })
  check('existing secrets are not rendered', await page.locator('input[type=password]').evaluateAll(inputs => inputs.every(input => input.value === '')))
  const input = page.getByRole('textbox', { name: 'MyAgent chat model', exact: true })
  await input.fill('edited-model')
  await page.evaluate(() => { window.myAgentFixture.failSave = true })
  await page.getByRole('button', { name: 'Save server settings', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: 'changed elsewhere' }).waitFor()
  check('failed save retains the draft', await input.inputValue() === 'edited-model')
  await page.getByRole('button', { name: 'Refresh status', exact: true }).click()
  check('status refresh retains the draft', await input.inputValue() === 'edited-model')
  await page.evaluate(() => { window.myAgentFixture.failSave = false })
  await page.getByRole('button', { name: 'Add shared folder', exact: true }).click()
  await page.getByRole('textbox', { name: 'Folder ID', exact: true }).nth(1).fill('new-documents')
  await page.getByRole('textbox', { name: 'Folder display name', exact: true }).nth(1).fill('New documents')
  await page.getByRole('button', { name: 'Choose folder', exact: true }).nth(1).click()
  await page.getByText('Indexing and visual extraction', { exact: true }).click()
  await page.getByRole('textbox', { name: 'Tesseract OCR executable path', exact: true }).fill('C:\\OCR\\tesseract.exe')
  await page.getByRole('spinbutton', { name: 'Maximum pages per file (0 = unlimited)', exact: true }).fill('100')
  await page.getByRole('spinbutton', { name: 'Visual extraction timeout (seconds)', exact: true }).fill('45')
  await page.getByRole('button', { name: 'Save server settings', exact: true }).click()
  await page.waitForFunction(() => window.myAgentFixture.saves.length === 1)
  check('root edits target the shared folder settings', await page.evaluate(() => window.myAgentFixture.saves[0].rag.roots[1].path === 'C:\\New documents'))
  check('extraction controls are included in the settings save', await page.evaluate(() => window.myAgentFixture.saves[0].rag.tesseractPath === 'C:\\OCR\\tesseract.exe' && window.myAgentFixture.saves[0].rag.maxPages === 100 && window.myAgentFixture.saves[0].rag.visualExtractionTimeoutSeconds === 45))
  check('restart requirement is visible', await page.getByRole('status').filter({ hasText: 'Restart required' }).isVisible())
  check('saving does not restart the server', await page.evaluate(() => window.myAgentFixture.controls.length === 0))
  await page.getByRole('button', { name: 'Restart server', exact: true }).click()
  check('restart waits for explicit confirmation', await page.evaluate(() => window.myAgentFixture.controls.length === 0))
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Restart server', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm restart', exact: true }).click()
  await page.waitForFunction(() => window.myAgentFixture.controls.length === 1)
  await page.getByRole('textbox', { name: 'MyAgent server URL', exact: true }).fill('http://127.0.0.1:6000')
  check('unsaved connection disables server actions', await page.getByRole('button', { name: 'Start server', exact: true }).isDisabled())
  await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
  const selected = page.getByRole('region', { name: 'Selected-file readiness', exact: true })
  check('file checks do not run automatically', await page.evaluate(() => window.myAgentFixture.checks.length === 0))
  await selected.getByRole('button', { name: 'Check selected files', exact: true }).click()
  await selected.getByText('Needs indexing', { exact: true }).first().waitFor()
  check('file checks request snapshot verification', await page.evaluate(() => window.myAgentFixture.checks[0].verify === true))
  check('selected refresh requires consent', await selected.getByRole('button', { name: 'Refresh selected files', exact: true }).isDisabled())
  await selected.getByRole('checkbox').check()
  await selected.getByRole('button', { name: 'Refresh selected files', exact: true }).click()
  await selected.getByText('OCR executable is unavailable. Configure its path and retry.', { exact: true }).waitFor()
  check('selected refresh reports individual failures', await page.evaluate(() => window.myAgentFixture.refreshes[0].paths.length === 2))
  await selected.getByRole('button', { name: 'Retry failed files', exact: true }).click()
  await page.waitForFunction(() => window.myAgentFixture.refreshes.length === 2)
  check('retry targets only failed selected files', await page.evaluate(() => window.myAgentFixture.refreshes[1].paths.length === 1 && window.myAgentFixture.refreshes[1].paths[0].endsWith('report.pdf')))
  await page.getByRole('button', { name: 'Select only report', exact: true }).click()
  await selected.getByText('1 individual files selected', { exact: true }).waitFor()
  check('a new selection requires new consent', await selected.getByRole('button', { name: 'Refresh selected files', exact: true }).isDisabled())
  await page.setViewportSize({ width: 300, height: 800 })
  await page.getByRole('heading', { name: 'Server status', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: path.join(output, 'myagent-300-status.png') })
  await page.screenshot({ path: path.join(output, 'myagent-300-light.png'), fullPage: true })
  const overflow = () => page.evaluate(() => [...document.querySelectorAll('input,select,button')].filter(e => e.getClientRects().length).filter(e => { const b = e.getBoundingClientRect(); return b.left < -1 || b.right > innerWidth + 1 }).map(e => e.outerHTML.slice(0, 100)))
  check('300px form fits without control overflow', (await overflow()).length === 0)
  await page.getByRole('button', { name: 'Arabic dark', exact: true }).click()
  await page.screenshot({ path: path.join(output, 'myagent-300-arabic-dark.png'), fullPage: true })
  check('Arabic form fits without control overflow', (await overflow()).length === 0)
  assert.deepEqual(errors, [], 'No renderer errors: ' + errors.join('; '))
  check('no renderer errors', errors.length === 0)
} finally { await browser.close(); await server.close() }
