import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import { pathToFileURL } from 'node:url'
import { createRequire } from 'node:module'
import { Worker } from 'node:worker_threads'
const root=process.env.NAWA_ANALYTICS_BUILD,project=process.env.NAWA_ANALYTICS_PROJECT
if(!root||!project)throw new Error('Use node tools/analytics/test.mjs.')
const load=name=>import(pathToFileURL(path.join(root,'apps/shell/src/main/analytics',name+'.mjs')).href)
const {AnalyticsEngine}=await load('engine'),{decimal,scaled,display,divide}=await load('numeric'),{delimited,jsonRecord,jsonArray,xmlFragments}=await load('stream'),{settings}=await load('validation')
const {DEFAULT_ANALYTICS_SETTINGS}=await import(pathToFileURL(path.join(root,'apps/shell/src/shared/analytics-api.mjs')).href)
const require=createRequire(path.join(project,'package.json')),JSZip=require('jszip')
async function fixture(fn,options={}){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'nawa-analytics-case-')),source=path.join(directory,'source'),state=path.join(directory,'state');await fs.mkdir(source);await fs.mkdir(state);let cancelled=false;const engine=new AnalyticsEngine(path.join(state,'data.sqlite3'),[source],{...DEFAULT_ANALYTICS_SETTINGS,...options},()=>{if(cancelled)throw new Error('Cancelled')});try{return await fn({engine,source,state,directory,cancel:()=>{cancelled=true}})}finally{engine.close();await fs.rm(directory,{recursive:true,force:true})}}
async function importCsv(ctx,name,text){const file=path.join(ctx.source,name);await fs.writeFile(file,text);await ctx.engine.execute({action:'import',folder:ctx.source});return ctx.engine.store.datasets([file])[0].data}
async function approve(ctx,d,patch={}){const policy={...d.policy,grain:'One input detail record',confirmed:true,...patch};return ctx.engine.execute({action:'review',payload:{datasetId:d.id,expectedGeneration:d.generation,policy}})}
const run=async(ctx,d,payload)=> (await ctx.engine.execute({action:'query',paths:[d.path],payload:{datasetIds:[d.id],...payload}})).value
const chunks=async function*(value,width=1){for(let i=0;i<value.length;i+=width)yield value.slice(i,i+width)}
const limits={maxRows:100,maxColumns:20,maxBytes:1024*1024,check:()=>{}}

test('decimal lexemes, scientific notation, exact scales and BigInt display',()=>{assert.deepEqual(decimal('1.23e2'),{coefficient:123n,scale:0});assert.equal(scaled('0.10',2),10n);assert.equal(display(-125n,2),'-1.25');assert.equal(divide(1n,8n,2),'0.13');assert.equal(divide(1n,0n),null);assert.throws(()=>scaled('1.234',2),/No rounding/);assert.throws(()=>scaled('9223372036854775808',0),/64-bit/);assert.throws(()=>decimal('1,234'),/unambiguous/)})
test('settings are bounded and do not change embedding configuration',()=>{assert.equal(settings({}).maxFileMiB,2048);assert.throws(()=>settings({maxRows:-1}));assert.throws(()=>settings({queryTimeoutSeconds:99999}))})
test('streaming CSV retains quoted multiline records across every character boundary',async()=>{const rows=[];for await(const row of delimited(chunks('id,text\r\n001,"a\r\nb"\r\n002,"x""y"\r\n'),',',limits))rows.push(row);assert.equal(rows.length,3);assert.equal(rows[1].cells[2].value,'a\r\nb');assert.equal(rows[2].cells[2].value,'x"y');assert.equal(rows[1].cells[1].value,'001');await assert.rejects(async()=>{for await(const _ of delimited(chunks('a\n"oops'),',',limits)){}},/Unclosed/)})
test('lossless JSON preserves large numbers and nested JSON without flattening arrays',()=>{const r=jsonRecord('{"id":9007199254740993,"amount":0.10,"nested":{"a":[1,2]},"s":"\\u65e5"}');assert.equal(r.id.value,'9007199254740993');assert.equal(r.amount.value,'0.10');assert.equal(r.nested.value,'{"a":[1,2]}');assert.equal(r.s.value,'日');assert.throws(()=>jsonRecord('{"a":1,"a":2}'),/Duplicate/);assert.throws(()=>jsonRecord('{"a":01}'))})
test('streaming JSON array rejects truncation and trailing commas',async()=>{const rows=[];for await(const row of jsonArray(chunks('[{"a":1},{"a":"x}y"}]'),limits))rows.push(row);assert.equal(rows.length,2);await assert.rejects(async()=>{for await(const _ of jsonArray(chunks('[{"a":1},]'),limits)){}},/Expected/);await assert.rejects(async()=>{for await(const _ of jsonArray(chunks('[{"a":1}'),limits)){}},/Incomplete/)})
test('streaming XML keeps complete rows and rejects DTDs and mismatched tags',async()=>{const bytes=async function*(s){for await(const part of chunks(s,2))yield Buffer.from(part)};const rows=[];for await(const x of xmlFragments(bytes('<s><row r="1"><c><v>12</v></c></row><row r="2"/></s>'),'row',limits))rows.push(x);assert.equal(rows.length,2);await assert.rejects(async()=>{for await(const _ of xmlFragments(bytes('<!DOCTYPE s><s/>'),'row',limits)){}},/forbidden/);await assert.rejects(async()=>{for await(const _ of xmlFragments(bytes('<s><row></s>'),'row',limits)){}},/Mismatched/)})
test('imports require human schema review; SQL cannot analyze unreviewed rows',async()=>fixture(async ctx=>{const d=await importCsv(ctx,'sales.csv','id,amount\n001,0.10\n002,0.20\n');assert.equal(d.status,'needs-review');assert.equal(d.policy.columns[0].type,'text');await assert.rejects(()=>run(ctx,d,{metrics:[{op:'count',as:'n'}]}),/not analytics-ready/);const ready=await approve(ctx,d,{key:['c0']});assert.equal(ready.rows,2);assert.equal(ready.excludedRows,1);const q=await run(ctx,ready,{metrics:[{op:'sum',column:'c1',as:'total'},{op:'count',as:'n'}]});assert.equal(q.rows[0].total,'0.3');assert.equal(q.rows[0].n,'2');assert.equal(q.inputSampled,false)}))
test('SUM remains exact above 64-bit total; large IDs and integers do not pass through Number',async()=>fixture(async ctx=>{const d=await importCsv(ctx,'big.csv','identifier,value\n9007199254740993,9000000000000000000\n9007199254740994,9000000000000000000\n');const ready=await approve(ctx,d);const q=await run(ctx,ready,{metrics:[{op:'sum',column:'c1',as:'total'}]});assert.equal(q.rows[0].total,'18000000000000000000');const detail=await run(ctx,ready,{columns:['c0']});assert.equal(detail.rows[0].c0,'9007199254740993')}))
test('query parameters resist SQL injection and raw SQL is not exposed',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'names.csv','name,value\nnormal,1\n"x\'); DROP TABLE analytics_files; --",2\n'));const q=await run(ctx,d,{filters:[{column:'c0',op:'eq',value:"x'); DROP TABLE analytics_files; --"}],metrics:[{op:'sum',column:'c1',as:'total'}]});assert.equal(q.rows[0].total,'2');assert.ok(ctx.engine.store.file(d.path));await assert.rejects(()=>run(ctx,d,{sql:'ATTACH DATABASE secret'}),/Raw SQL/);await assert.rejects(()=>run(ctx,d,{metrics:[{op:'sum',column:'c1); DROP TABLE x',as:'total'}]}),/Unknown column/)}))
test('population aggregates are complete even when output groups are capped for display',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'groups.csv','group,value\nA,1\nB,2\nC,3\nD,4\n'));const q=await run(ctx,d,{groupBy:[{column:'c0',as:'category'}],metrics:[{op:'sum',column:'c1',as:'total'}],orderBy:[{column:'total',descending:true}],limit:2});assert.equal(q.population.matchedRows,4);assert.equal(q.totalResultRows,4);assert.equal(q.rows.length,2);assert.equal(q.rows[0].total,'4');assert.equal(q.outputTruncated,true);assert.equal(q.inputSampled,false)}))
test('NULL count, mean and exact quantiles have explicit denominator behavior',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'null.csv','id,value\na,1\nb,2\nc,\nd,9\n'));const q=await run(ctx,d,{metrics:[{op:'count',as:'all'},{op:'count',column:'c1',as:'non_null'},{op:'mean',column:'c1',as:'mean'}]});assert.equal(q.rows[0].all,'4');assert.equal(q.rows[0].non_null,'3');assert.equal(q.rows[0].mean.value,'4.000000');const s=(await ctx.engine.execute({action:'analyze',paths:[d.path],payload:{datasetIds:[d.id],method:'describe',column:'c1'}})).value;assert.equal(s.summary.missing,1);assert.equal(s.summary.median.value,'2.000000');assert.equal(s.summary.q1.value,'1.500000');assert.equal(s.summary.sampleVariance,19)}))

test('unselected datasets and saved receipts are denied even when present in the database',async()=>fixture(async ctx=>{const a=await approve(ctx,await importCsv(ctx,'a.csv','id,value\na,1\n'));const b=await approve(ctx,await importCsv(ctx,'b.csv','id,value\nb,2\n'));await assert.rejects(()=>ctx.engine.execute({action:'query',paths:[a.path],payload:{datasetIds:[b.id],metrics:[{op:'count',as:'n'}]}}),/selected-file scope/);const q=await run(ctx,b,{metrics:[{op:'count',as:'n'}]});await assert.rejects(()=>ctx.engine.execute({action:'result',paths:[a.path],payload:{resultId:q.id}}),/selected-file scope/);const catalog=(await ctx.engine.execute({action:'discover',paths:[a.path],payload:{}})).value;assert.equal(catalog.datasets.length,1);assert.equal(catalog.datasets[0].id,a.id)}))
test('mixed currencies require grouping or a complete single-currency filter',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'money.csv','id,amount,currency\na,10,JPY\nb,20,USD\n'),{currencyColumn:'c2'});await assert.rejects(()=>run(ctx,d,{metrics:[{op:'sum',column:'c1',as:'total'}]}),/Currency scope/);const grouped=await run(ctx,d,{groupBy:[{column:'c2',as:'currency'}],metrics:[{op:'sum',column:'c1',as:'total'}]});assert.equal(grouped.rows.length,2);const filtered=await run(ctx,d,{filters:[{column:'c2',op:'eq',value:'JPY'}],metrics:[{op:'sum',column:'c1',as:'total'}]});assert.equal(filtered.rows[0].total,'10')}))
test('declared keys reject duplicates and nulls before publishing an approved table',async()=>fixture(async ctx=>{let d=await importCsv(ctx,'dups.csv','id,value\na,1\na,2\n');await assert.rejects(()=>approve(ctx,d,{key:['c0']}),/not unique/);assert.equal(ctx.engine.store.dataset(d.id).data.status,'needs-review');d=await importCsv(ctx,'missing.csv','id,value\n,1\na,2\n');await assert.rejects(()=>approve(ctx,d,{key:['c0']}),/missing values/)}))
test('unions require identical schemas and disjoint business keys',async()=>fixture(async ctx=>{const a=await approve(ctx,await importCsv(ctx,'a.csv','id,value\na,10\n'),{key:['c0']});const b=await approve(ctx,await importCsv(ctx,'b.csv','id,value\nb,20\n'),{key:['c0']});const q=(await ctx.engine.execute({action:'query',paths:[a.path,b.path],payload:{datasetIds:[a.id,b.id],metrics:[{op:'sum',column:'c1',as:'total'}]}})).value;assert.equal(q.rows[0].total,'30');assert.equal(q.sources.length,2);const c=await approve(ctx,await importCsv(ctx,'c.csv','id,value\na,30\n'),{key:['c0']});await assert.rejects(()=>ctx.engine.execute({action:'query',paths:[a.path,c.path],payload:{datasetIds:[a.id,c.id],metrics:[{op:'count',as:'n'}]}}),/Overlapping row keys/)}))
test('identical copied exports and missing-key unions are blocked',async()=>fixture(async ctx=>{const a=await approve(ctx,await importCsv(ctx,'a.csv','id,value\na,10\n'),{key:['c0']});const b=await approve(ctx,await importCsv(ctx,'copy.csv','id,value\na,10\n'),{key:['c0']});await assert.rejects(()=>ctx.engine.execute({action:'query',paths:[a.path,b.path],payload:{datasetIds:[a.id,b.id],metrics:[{op:'count',as:'n'}]}}),/Identical source-file/);const c=await approve(ctx,await importCsv(ctx,'nokey.csv','id,value\nc,20\n'));await assert.rejects(()=>ctx.engine.execute({action:'query',paths:[c.path,a.path],payload:{datasetIds:[c.id,a.id],metrics:[{op:'count',as:'n'}]}}),/schemas|key/)}))
test('many-to-one joins preserve fact grain and report unmatched left rows',async()=>fixture(async ctx=>{const a=await approve(ctx,await importCsv(ctx,'lines.csv','id,product,amount\nl1,p1,10\nl2,p1,20\nl3,p2,30\n'),{key:['c0']});const b=await approve(ctx,await importCsv(ctx,'products.csv','product,category\np1,Alpha\n'),{key:['c0']});const q=(await ctx.engine.execute({action:'query',paths:[a.path,b.path],payload:{datasetIds:[a.id],join:{datasetId:b.id,leftKeys:['c1'],rightKeys:['c0'],kind:'left'},groupBy:[{column:'right.c1',as:'category'}],metrics:[{op:'sum',column:'c2',as:'total'}]}})).value;assert.equal(q.population.matchedRows,3);assert.equal(q.population.unmatchedJoinRowsBeforeFilters,1);assert.equal(q.rows.find(r=>r.category==='Alpha').total,'30')}))
test('join fan-out and summing repeated lookup-side measures are rejected',async()=>fixture(async ctx=>{const a=await approve(ctx,await importCsv(ctx,'facts.csv','product,amount\np1,10\np1,20\n'));const b=await approve(ctx,await importCsv(ctx,'lookup.csv','product,price\np1,4\np1,5\n'));const spec={datasetIds:[a.id],join:{datasetId:b.id,leftKeys:['c0'],rightKeys:['c0'],kind:'left'},metrics:[{op:'sum',column:'c1',as:'total'}]};await assert.rejects(()=>ctx.engine.execute({action:'query',paths:[a.path,b.path],payload:spec}),/multiply fact rows/);const c=await approve(ctx,await importCsv(ctx,'unique.csv','product,price\np1,4\n'),{key:['c0']});await assert.rejects(()=>ctx.engine.execute({action:'query',paths:[a.path,c.path],payload:{...spec,join:{...spec.join,datasetId:c.id},metrics:[{op:'sum',column:'right.c1',as:'total'}]}}),/double-count/)}))
test('same-length edits with restored mtime invalidate SQL and historical receipts',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'file.csv','id,value\na,10\n'));const q=await run(ctx,d,{metrics:[{op:'sum',column:'c1',as:'total'}]});const s=await fs.stat(d.path);await fs.writeFile(d.path,'id,value\na,90\n');await fs.utimes(d.path,s.atime,s.mtime);const status=await ctx.engine.execute({action:'statuses',paths:[d.path],verify:true});assert.equal(status[0].state,'changed');await assert.rejects(()=>run(ctx,d,{metrics:[{op:'count',as:'n'}]}),/changed after import/);await assert.rejects(()=>ctx.engine.execute({action:'result',paths:[d.path],payload:{resultId:q.id}}),/changed after import/)}))
test('re-importing unchanged files reuses the approved generation without embeddings',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'same.csv','id,value\na,10\n'));const p=await ctx.engine.execute({action:'import',folder:ctx.source});assert.equal(p.unchanged,1);assert.equal(ctx.engine.store.dataset(d.id).data.generation,d.generation);assert.equal(ctx.engine.store.dataset(d.id).data.status,'ready')}))
test('invalid typed values fail the entire approval instead of dropping bad records',async()=>fixture(async ctx=>{const d=await importCsv(ctx,'mixed.csv','id,amount\na,10\nb,oops\n');const columns=d.policy.columns.map((c,i)=>i===1?{...c,type:'integer',role:'measure'}:c);await assert.rejects(()=>approve(ctx,d,{columns}),/Row 3/);assert.equal(ctx.engine.store.dataset(d.id).typedTable,null);assert.equal(ctx.engine.store.dataset(d.id).data.rows,0)}))
test('explicit source-row exclusions prevent subtotal double counting and are audited',async()=>fixture(async ctx=>{const d=await importCsv(ctx,'totals.csv','item,value\na,10\nb,20\nTotal,30\n');assert.ok(d.warnings.some(w=>w.includes('subtotal')));const ready=await approve(ctx,d,{skipRows:[4]});assert.equal(ready.excludedRows,2);const q=await run(ctx,ready,{metrics:[{op:'sum',column:'c1',as:'total'}]});assert.equal(q.rows[0].total,'30');assert.equal(q.population.sourceRows[0].excludedByPolicy,2)}))
test('period grouping uses validated dates and numeric aggregate ordering is not lexicographic',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'dates.csv','posted,value\n2026-01-01,2\n2026-02-01,10\n'));const q=await run(ctx,d,{groupBy:[{column:'c0',period:'month',as:'month'}],metrics:[{op:'sum',column:'c1',as:'total'}],orderBy:[{column:'total',descending:true}]});assert.equal(q.rows[0].month,'2026-02');assert.equal(q.rows[0].total,'10')}))
test('period contributions reconcile exactly; percentages use explicit denominators',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'periods.csv','date,product,amount\n2026-01-02,A,100\n2026-01-02,B,100\n2026-04-02,A,60\n2026-04-02,B,110\n'));const r=(await ctx.engine.execute({action:'analyze',paths:[d.path],payload:{datasetIds:[d.id],method:'compare-periods',column:'c2',dateColumn:'c0',groupColumn:'c1',current:{from:'2026-04-01',to:'2026-07-01'},previous:{from:'2026-01-01',to:'2026-04-01'}}})).value;assert.equal(r.summary.current,'170');assert.equal(r.summary.previous,'200');assert.equal(r.summary.change,'-30');assert.equal(r.summary.reconciled,true);assert.equal(r.rows[0].group,'A');assert.equal(r.rows[0].change,'-40');assert.equal(r.rows[0].contributionToNetChangePercent,'133.3333')}))
test('correlation uses all valid pairs and does not invent significance or causation',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'pairs.csv','x,y\n1,2\n2,4\n3,6\n4,\n'));const r=(await ctx.engine.execute({action:'analyze',paths:[d.path],payload:{datasetIds:[d.id],method:'correlation',column:'c0',otherColumn:'c1'}})).value;assert.equal(r.summary.pairedRows,3);assert.equal(r.summary.excludedMissingPairs,1);assert.ok(Math.abs(r.summary.coefficient-1)<1e-14);assert.match(r.summary.interpretation,/not causation/)}))
test('drill-down retains original filters and returns exact source row references',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'drill.csv','category,value\nA,1\nB,2\nA,3\n'));const q=await run(ctx,d,{filters:[{column:'c0',op:'eq',value:'A'}],metrics:[{op:'sum',column:'c1',as:'total'}]});const detail=(await ctx.engine.execute({action:'drill',paths:[d.path],payload:{resultId:q.id,filters:[{column:'c1',op:'gt',value:'1'}],columns:['c0','c1']}})).value;assert.equal(detail.rows.length,1);assert.equal(detail.rows[0].__source_row,'4');assert.equal(detail.rows[0].c1,'3');assert.equal(detail.population.matchedRows,1)}))
test('clearing analytical data removes receipts but preserves source files, chats and RAG data',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'clear.csv','id,value\na,1\n'));const q=await run(ctx,d,{metrics:[{op:'count',as:'n'}]});await fs.writeFile(path.join(ctx.state,'conversations.sqlite3'),'chat sentinel');await fs.writeFile(path.join(ctx.state,'rag.sqlite3'),'rag sentinel');await ctx.engine.execute({action:'clear',folder:ctx.source});assert.equal(ctx.engine.store.result(q.id),undefined);assert.equal(ctx.engine.store.datasets().length,0);assert.equal(await fs.readFile(d.path,'utf8'),'id,value\na,1\n');assert.equal(await fs.readFile(path.join(ctx.state,'conversations.sqlite3'),'utf8'),'chat sentinel');assert.equal(await fs.readFile(path.join(ctx.state,'rag.sqlite3'),'utf8'),'rag sentinel')}))
test('a row-limit failure does not publish a partially imported source',async()=>fixture(async ctx=>{await fs.writeFile(path.join(ctx.source,'too-big.csv'),'id,value\na,1\nb,2\nc,3\n');const p=await ctx.engine.execute({action:'import',folder:ctx.source});assert.equal(p.failed,1);assert.equal(ctx.engine.store.datasets().length,0);assert.equal(ctx.engine.store.files()[0].state,'failed')},{maxRows:2}))
test('hidden files and subdirectories are excluded unless recursion is explicitly enabled',async()=>fixture(async ctx=>{await fs.mkdir(path.join(ctx.source,'sub'));await fs.writeFile(path.join(ctx.source,'sub','data.csv'),'id,value\na,1\n');await fs.writeFile(path.join(ctx.source,'.hidden.csv'),'id,value\na,2\n');let p=await ctx.engine.execute({action:'import',folder:ctx.source});assert.equal(p.scanned,0);p=await ctx.engine.execute({action:'import',folder:ctx.source,recursive:true});assert.equal(p.scanned,1);assert.equal(ctx.engine.store.datasets().length,1)}))
test('malformed UTF-8 and JSON truncation fail instead of publishing corrupted text',async()=>fixture(async ctx=>{await fs.writeFile(path.join(ctx.source,'bad.csv'),Buffer.from([0x61,0x0a,0xc3,0x28]));await fs.writeFile(path.join(ctx.source,'bad.json'),'[{"a":1},');const p=await ctx.engine.execute({action:'import',folder:ctx.source});assert.equal(p.failed,2);assert.equal(ctx.engine.store.datasets().length,0)}))
async function xlsx(file,{named=true,formula=false,missingCache=false,hidden=false,duplicateString=false}={}){
  const zip=new JSZip()
  zip.file('xl/workbook.xml','<workbook xmlns:r="urn:r"><workbookPr date1904="0"/><sheets><sheet name="Sales" sheetId="1" r:id="rId1"/></sheets></workbook>')
  zip.file('xl/_rels/workbook.xml.rels','<Relationships><Relationship Id="rId1" Type="http://x/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://x/styles" Target="styles.xml"/><Relationship Id="rId3" Type="http://x/sharedStrings" Target="sharedStrings.xml"/></Relationships>')
  zip.file('xl/sharedStrings.xml','<sst><si><t>id</t></si><si><t>amount</t></si><si><t>posted</t></si><si><t>001</t></si><si><r><t>00</t></r><r><t>2</t></r></si></sst>')
  zip.file('xl/styles.xml','<styleSheet><cellXfs count="2"><xf numFmtId="0"/><xf numFmtId="14"/></cellXfs></styleSheet>')
  zip.file('xl/worksheets/sheet1.xml',`<worksheet><sheetData><row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c><c r="C1" t="s"><v>2</v></c></row><row r="2"><c r="A2" t="s"><v>3</v></c><c r="B2">${formula?'<f>1+2</f>':''}${missingCache?'':'<v>3.25</v>'}</c><c r="C2" s="1"><v>45292</v></c></row><row r="3" ${hidden?'hidden="1"':''}><c r="A3" t="s"><v>${duplicateString?'3':'4'}</v></c><c r="B3"><v>4.75</v></c><c r="C3" s="1"><v>45293</v></c></row>${named?'<row r="4"><c r="A4" t="inlineStr"><is><t>Total</t></is></c><c r="B4"><v>8</v></c></row>':''}</sheetData>${named?'<tableParts count="1"><tablePart r:id="table1" xmlns:r="urn:r"/></tableParts>':''}</worksheet>`)
  if(named){zip.file('xl/worksheets/_rels/sheet1.xml.rels','<Relationships><Relationship Id="table1" Type="http://x/table" Target="../tables/table1.xml"/></Relationships>');zip.file('xl/tables/table1.xml','<table name="SalesTable" displayName="SalesTable" ref="A1:C4" totalsRowCount="1"><tableColumns><tableColumn id="1" name="id"/><tableColumn id="2" name="amount"/><tableColumn id="3" name="posted"/></tableColumns></table>')}
  await fs.writeFile(file,await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE'}))
}
test('XLSX streams named tables, shared strings, dates and excludes declared totals',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'sales.xlsx');await xlsx(file);const p=await ctx.engine.execute({action:'import',folder:ctx.source});assert.equal(p.failed,0,JSON.stringify(ctx.engine.store.files()));const d=ctx.engine.store.datasets([file])[0].data;assert.equal(d.kind,'xlsx-named-table');assert.equal(d.policy.columns[2].type,'date');assert.equal(d.preview[1].values[2],'2024-01-01');assert.equal(d.preview[2].values[0],'002');const ready=await approve(ctx,d,{key:['c0']});const q=await run(ctx,ready,{metrics:[{op:'sum',column:'c1',as:'total'}]});assert.equal(q.rows[0].total,'8.00');assert.equal(ready.rows,2)}))
test('XLSX formulas are rejected by default; explicit cache approval is recorded',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'formula.xlsx');await xlsx(file,{formula:true});await ctx.engine.execute({action:'import',folder:ctx.source});const d=ctx.engine.store.datasets([file])[0].data;await assert.rejects(()=>approve(ctx,d),/contains a formula/);const ready=await approve(ctx,d,{formulaPolicy:'saved-cache'});assert.equal(ready.formulaCells,1);assert.ok(ready.warnings.some(w=>w.includes('explicitly accepted')))}))
test('missing formula caches cannot be treated as zeros, even with cache approval',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'missing.xlsx');await xlsx(file,{formula:true,missingCache:true});await ctx.engine.execute({action:'import',folder:ctx.source});const d=ctx.engine.store.datasets([file])[0].data;await assert.rejects(()=>approve(ctx,d,{formulaPolicy:'saved-cache'}),/no saved value/)}))
test('hidden XLSX rows follow an explicit policy and excluded counts are visible',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'hidden.xlsx');await xlsx(file,{hidden:true});await ctx.engine.execute({action:'import',folder:ctx.source});const d=ctx.engine.store.datasets([file])[0].data;const a=await approve(ctx,d);assert.equal(a.rows,1);assert.equal(a.excludedRows,2);const b=await approve(ctx,a,{includeHiddenRows:true});assert.equal(b.rows,2)}))
test('unnamed worksheet regions remain review-required rather than guessed complete tables',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'region.xlsx');await xlsx(file,{named:false});await ctx.engine.execute({action:'import',folder:ctx.source});const d=ctx.engine.store.datasets([file])[0].data;assert.equal(d.kind,'xlsx-sheet-region');assert.equal(d.status,'needs-review');assert.ok(d.warnings.some(w=>w.includes('No named Excel table')))}))
test('corrupted XLSX ZIP content is rejected by CRC or decompression validation',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'corrupt.xlsx');await xlsx(file);const b=await fs.readFile(file);let central=0;for(;;){central=b.indexOf(Buffer.from([0x50,0x4b,0x01,0x02]),central);assert.ok(central>=0,'workbook central entry exists');const length=b.readUInt16LE(central+28);if(b.subarray(central+46,central+46+length).toString()==='xl/workbook.xml')break;central+=46+length+b.readUInt16LE(central+30)+b.readUInt16LE(central+32)}b.writeUInt32LE(1234,central+16);await fs.writeFile(file,b);const p=await ctx.engine.execute({action:'import',folder:ctx.source});assert.equal(p.failed,1);assert.equal(ctx.engine.store.datasets().length,0)}))
test('schema generations invalidate previous receipts after policy changes',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'policy.csv','id,value\na,1\nb,2\n'));const q=await run(ctx,d,{metrics:[{op:'sum',column:'c1',as:'total'}]});await approve(ctx,d,{skipRows:[3]});await assert.rejects(()=>ctx.engine.execute({action:'result',paths:[d.path],payload:{resultId:q.id}}),/generation changed/)}))
test('constant-column correlation returns undefined, not invented evidence',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'constant.csv','x,y\n1,2\n1,3\n'));const q=(await ctx.engine.execute({action:'analyze',paths:[d.path],payload:{datasetIds:[d.id],method:'correlation',column:'c0',otherColumn:'c1'}})).value;assert.equal(q.summary.coefficient,null);assert.ok(q.warnings.some(w=>w.includes('undefined')))}))
test('deleted files are pruned after complete enumeration; other roots remain isolated',async()=>fixture(async ctx=>{const d=await importCsv(ctx,'remove.csv','id,value\na,1\n');await fs.unlink(d.path);await ctx.engine.execute({action:'import',folder:ctx.source});assert.equal(ctx.engine.store.dataset(d.id),undefined);await assert.rejects(()=>ctx.engine.execute({action:'import',folder:ctx.state}),/outside/)}))
test('statistical operations never make an embedding/network request',async()=>fixture(async ctx=>{const original=globalThis.fetch;globalThis.fetch=()=>{throw new Error('Network must not be used')};try{const d=await approve(ctx,await importCsv(ctx,'offline.csv','id,value\na,1\nb,2\n'));const q=await run(ctx,d,{metrics:[{op:'mean',column:'c1',as:'mean'}]});assert.equal(q.rows[0].mean.value,'1.500000')}finally{globalThis.fetch=original}}))
test('schema review cannot expand a named table beyond its imported source bounds',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'bounds.xlsx');await xlsx(file);await ctx.engine.execute({action:'import',folder:ctx.source});const d=ctx.engine.store.datasets([file])[0].data;await assert.rejects(()=>approve(ctx,d,{lastRow:99}),/source table bounds/);await assert.rejects(()=>approve(ctx,d,{lastRow:null}),/source table bounds/);assert.equal(ctx.engine.store.dataset(d.id).data.status,'needs-review')}))
test('statistical requests reject joins instead of silently dropping them',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'stats.csv','x,y\n1,2\n2,4\n'));await assert.rejects(()=>ctx.engine.execute({action:'analyze',paths:[d.path],payload:{datasetIds:[d.id],method:'describe',column:'c0',join:{datasetId:d.id}}}),/do not accept joins/)}))
test('cooperative cancellation rolls back an unfinished file generation',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'cancel.csv');await fs.writeFile(file,'id,value\n'+Array.from({length:4000},(_,i)=>`id${i},${i}`).join('\n'));let cancel=false;const e=new AnalyticsEngine(ctx.engine.databasePath,[ctx.source],DEFAULT_ANALYTICS_SETTINGS,()=>{if(cancel)throw new Error('Cancelled by test')},p=>{if(p.rows>=1000)cancel=true});try{await assert.rejects(()=>e.execute({action:'import',folder:ctx.source}),/Cancelled/);assert.equal(e.store.datasets([file]).length,0);assert.equal(e.store.file(file).state,'failed')}finally{e.close()}}))
test('source modification during import never publishes mismatched data',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'race.csv');await fs.writeFile(file,'id,value\n'+Array.from({length:2000},(_,i)=>`id${i},${i}`).join('\n'));let changed=false;const sync=require('node:fs');const e=new AnalyticsEngine(ctx.engine.databasePath,[ctx.source],DEFAULT_ANALYTICS_SETTINGS,()=>{},p=>{if(p.rows>=1000&&!changed){changed=true;sync.appendFileSync(file,'\nid9999,99')}});try{const p=await e.execute({action:'import',folder:ctx.source});assert.equal(p.failed,1);assert.equal(e.store.datasets([file]).length,0);assert.match(e.store.file(file).error,/Source changed/)}finally{e.close()}}))
test('recovery removes orphan tables and makes interrupted imports retryable',async()=>fixture(async ctx=>{const file=path.join(ctx.source,'recovery.csv');await fs.writeFile(file,'id,value\na,1\n');ctx.engine.store.putFile({path:file,hash:'old',size:1,mtime:0,ctime:0,state:'importing',error:'',imported:0});const orphan='ar_'+'a'.repeat(32);ctx.engine.store.db.exec(`CREATE TABLE "${orphan}"(row INTEGER PRIMARY KEY,data TEXT) STRICT`);ctx.engine.store.recover();assert.equal(ctx.engine.store.file(file).state,'failed');assert.equal(ctx.engine.store.db.prepare('SELECT 1 FROM sqlite_master WHERE name=?').get(orphan),undefined);await ctx.engine.execute({action:'import',folder:ctx.source});assert.equal(ctx.engine.store.file(file).state,'needs-review')}))
test('excessive aggregate groups fail rather than returning a partial population',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'many.csv','id,value\n'+Array.from({length:101},(_,i)=>`id${i},1`).join('\n')));await assert.rejects(()=>run(ctx,d,{groupBy:[{column:'c0',as:'group'}],metrics:[{op:'count',as:'n'}]}),/group/i)},{maxGroups:100}))
test('worker observes cancellation flags and exits without publishing data',async()=>fixture(async ctx=>{const flag=new SharedArrayBuffer(4);Atomics.store(new Int32Array(flag),0,1);const worker=new Worker(path.join(root,'apps/shell/src/main/analytics/worker.mjs'),{workerData:{databasePath:ctx.engine.databasePath,roots:[ctx.source],settings:DEFAULT_ANALYTICS_SETTINGS,job:{action:'import',folder:ctx.source},cancel:flag,deadline:Date.now()+10000}});const messages=[];await new Promise((resolve,reject)=>{worker.on('message',m=>messages.push(m));worker.once('error',reject);worker.once('exit',resolve)});assert.ok(messages.some(m=>m.error?.includes('cancelled')));assert.equal(ctx.engine.store.datasets().length,0)}))
test('worker deadline is enforced before analytical work',async()=>fixture(async ctx=>{const worker=new Worker(path.join(root,'apps/shell/src/main/analytics/worker.mjs'),{workerData:{databasePath:ctx.engine.databasePath,roots:[ctx.source],settings:DEFAULT_ANALYTICS_SETTINGS,job:{action:'discover',paths:[],payload:{}},cancel:new SharedArrayBuffer(4),deadline:Date.now()-1}});const messages=[];await new Promise((resolve,reject)=>{worker.on('message',m=>messages.push(m));worker.once('error',reject);worker.once('exit',resolve)});assert.ok(messages.some(m=>m.error?.includes('time budget')))}))
test('empty filtered population returns null numerical statistics instead of zeros',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'empty.csv','id,value\na,1\n'));const s=(await ctx.engine.execute({action:'analyze',paths:[d.path],payload:{datasetIds:[d.id],method:'describe',column:'c1',filters:[{column:'c0',op:'eq',value:'missing'}]}})).value;assert.equal(s.summary.count,0);assert.equal(s.summary.sum,null);assert.equal(s.summary.mean,null);assert.equal(s.summary.median,null);assert.equal(s.summary.sampleVariance,null)}))
test('ratio of complete totals computes weighted margin, not average row percentages',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'margin.csv','id,profit,revenue\na,10.00,100.00\nb,90.00,300.00\n'));const q=await run(ctx,d,{metrics:[{op:'ratio-of-sums',column:'c1',denominatorColumn:'c2',multiplyBy:100,as:'margin_percent'}]});assert.equal(q.rows[0].margin_percent.value,'25.000000');assert.equal(q.rows[0].margin_percent.rows,'2');assert.equal(q.inputSampled,false)}))
test('ratio of sums rejects missing values and reports undefined zero denominators',async()=>fixture(async ctx=>{let d=await approve(ctx,await importCsv(ctx,'ratio.csv','id,numerator,denominator\na,1,0\n'));let q=await run(ctx,d,{metrics:[{op:'ratio-of-sums',column:'c1',denominatorColumn:'c2',as:'ratio'}]});assert.equal(q.rows[0].ratio.value,null);assert.equal(q.rows[0].ratio.zeroDenominator,true);d=await approve(ctx,await importCsv(ctx,'missing-ratio.csv','id,numerator,denominator\na,1,2\nb,,4\n'));await assert.rejects(()=>run(ctx,d,{metrics:[{op:'ratio-of-sums',column:'c1',denominatorColumn:'c2',as:'ratio'}]}),/complete numerator/)}))
test('wide schemas are paginated without hiding the remaining columns',async()=>fixture(async ctx=>{const headers=Array.from({length:40},(_,i)=>`value${i}`).join(','),values=Array.from({length:40},(_,i)=>String(i)).join(',');const d=await importCsv(ctx,'wide.csv',headers+'\n'+values+'\n');const a=(await ctx.engine.execute({action:'describe',paths:[d.path],payload:{datasetId:d.id,columnLimit:16}})).value;assert.equal(a.policy.columns.length,16);assert.equal(a.totalColumns,40);assert.equal(a.nextColumnOffset,16);const b=(await ctx.engine.execute({action:'describe',paths:[d.path],payload:{datasetId:d.id,columnOffset:32,columnLimit:16}})).value;assert.equal(b.policy.columns.length,8);assert.equal(b.policy.columns[0].id,'c32');assert.equal(b.nextColumnOffset,null)}))
test('variance preserves small integer differences above JavaScript safe integer precision',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'stable.csv','value\n9007199254740993\n9007199254740994\n'));const q=(await ctx.engine.execute({action:'analyze',paths:[d.path],payload:{datasetIds:[d.id],method:'describe',column:'c0'}})).value;assert.equal(q.summary.sampleVariance,0.5);assert.equal(q.summary.mean.value,'9007199254740993.500000')}))
test('correlation centers exact integers before converting differences to floating point',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'stable-correlation.csv','x,y\n9007199254740993,9007199254740996\n9007199254740994,9007199254740998\n9007199254740995,9007199254741000\n'));const q=(await ctx.engine.execute({action:'analyze',paths:[d.path],payload:{datasetIds:[d.id],method:'correlation',column:'c0',otherColumn:'c1'}})).value;assert.ok(Math.abs(q.summary.coefficient-1)<1e-14)}))
test('Electron IPC harness denies foreign frames and agent-side import/review commands',async()=>fixture(async ctx=>{process.env.NAWA_ANALYTICS_HARNESS_USERDATA=ctx.state;const {electron,service}=await import('./service-harness.mjs');const sender=new electron.Sender(),s=service.registerAnalyticsIpc({roots:async()=>[ctx.source],isHomeSender:w=>w===sender});try{const handler=electron.handlers.get('nawa:analytics');await assert.rejects(()=>handler({sender,senderFrame:{}},'settings'),/only from/);await assert.rejects(()=>handler({sender,senderFrame:sender.mainFrame},'import',ctx.source,false,false),/Confirm local/);await assert.rejects(()=>s.selected(sender.id,[],'import',{},new AbortController().signal),/read-only analytical/);const cfg=await handler({sender,senderFrame:sender.mainFrame},'settings');assert.ok(cfg.databasePath.includes('analytics'));assert.equal(cfg.settings.maxFileMiB,2048)}finally{s.stop()}}))
test('Electron IPC harness uses real workers for local import, review, query and source receipts',async()=>fixture(async ctx=>{process.env.NAWA_ANALYTICS_HARNESS_USERDATA=ctx.state;const {electron,service}=await import('./service-harness.mjs'),sender=new electron.Sender(124),s=service.registerAnalyticsIpc({roots:async()=>[ctx.source],isHomeSender:w=>w===sender}),file=path.join(ctx.source,'workers.csv');await fs.writeFile(file,'id,value\na,10\nb,20\n');try{const handler=electron.handlers.get('nawa:analytics'),event={sender,senderFrame:sender.mainFrame};const p=await handler(event,'import',ctx.source,false,true);assert.equal(p.imported,1);const catalog=await handler(event,'catalog',ctx.source),d=catalog.datasets[0];await handler(event,'review',d.id,d.generation,{...d.policy,grain:'One worker fixture row',confirmed:true});const q=await s.selected(sender.id,[file],'query',{datasetIds:[d.id],metrics:[{op:'sum',column:'c1',as:'total'}]},new AbortController().signal);assert.equal(q.value.rows[0].total,'30');assert.equal(q.sources[0].path,file);assert.ok(sender.messages.length>0)}finally{s.stop()}}))
test('Electron supervisor cancels an owner writer through its shared cancellation flag',async()=>fixture(async ctx=>{process.env.NAWA_ANALYTICS_HARNESS_USERDATA=ctx.state;const {electron,service}=await import('./service-harness.mjs'),sender=new electron.Sender(125),s=service.registerAnalyticsIpc({roots:async()=>[ctx.source],isHomeSender:w=>w===sender});await fs.writeFile(path.join(ctx.source,'cancel-worker.csv'),'id,value\na,1\n');try{const handler=electron.handlers.get('nawa:analytics'),event={sender,senderFrame:sender.mainFrame};sender.once('sent',()=>s.cancel(sender.id));await assert.rejects(()=>handler(event,'import',ctx.source,false,true),/cancelled/i);assert.equal(s.progress().running,false)}finally{s.stop()}}))
test('Electron supervisor rejects result delivery after a workspace root is detached',async()=>fixture(async ctx=>{process.env.NAWA_ANALYTICS_HARNESS_USERDATA=ctx.state;const {electron,service}=await import('./service-harness.mjs'),sender=new electron.Sender(126);let roots=[ctx.source];const s=service.registerAnalyticsIpc({roots:async()=>roots,isHomeSender:w=>w===sender});await fs.writeFile(path.join(ctx.source,'detach.csv'),'id,value\na,1\n');try{const handler=electron.handlers.get('nawa:analytics'),event={sender,senderFrame:sender.mainFrame};sender.once('sent',()=>{roots=[]});await assert.rejects(()=>handler(event,'import',ctx.source,false,true),/permissions changed|cancelled/i)}finally{s.stop()}}))
test('overflowing REAL aggregates fail instead of serializing infinity as null',async()=>fixture(async ctx=>{const draft=await importCsv(ctx,'overflow.csv','value\n1e308\n1e308\n'),d=await approve(ctx,draft,{columns:draft.policy.columns.map(c=>({...c,type:'real',role:'measure'}))});await assert.rejects(()=>run(ctx,d,{metrics:[{op:'sum',column:'c0',as:'total'}]}),/non-finite/i)}))
test('undefined grouped ratios remain last when sorting descending',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'ratio-groups.csv','group,numerator,denominator\nA,1,0\nB,1,2\n'));const q=await run(ctx,d,{groupBy:[{column:'c0',as:'group'}],metrics:[{op:'ratio-of-sums',column:'c1',denominatorColumn:'c2',as:'ratio'}],orderBy:[{column:'ratio',descending:true}]});assert.equal(q.rows[0].group,'B');assert.equal(q.rows[1].ratio.value,null)}))
test('an importer version mismatch forces fresh review even with unchanged source bytes',async()=>fixture(async ctx=>{const d=await approve(ctx,await importCsv(ctx,'version.csv','id,value\na,1\n'));const old=ctx.engine.store.dataset(d.id);old.data.profile.importerVersion='older';ctx.engine.store.putDataset(old);const p=await ctx.engine.execute({action:'import',folder:ctx.source});assert.equal(p.imported,1);assert.equal(ctx.engine.store.dataset(d.id).data.status,'needs-review')}))
test('table-review catalog and selected-file coverage are paginated for large collections',async()=>fixture(async ctx=>{const paths=[];for(let i=0;i<26;i++){const file=path.join(ctx.source,`file${i}.csv`);paths.push(file);await fs.writeFile(file,'id,value\na,1\n')}await ctx.engine.execute({action:'import',folder:ctx.source});const a=await ctx.engine.execute({action:'catalog',folder:ctx.source});assert.equal(a.datasets.length,20);assert.equal(a.total,26);assert.equal(a.nextOffset,20);const b=await ctx.engine.execute({action:'catalog',folder:ctx.source,payload:{offset:20}});assert.equal(b.datasets.length,6);assert.equal(b.nextOffset,null);const discovered=(await ctx.engine.execute({action:'discover',paths,payload:{}})).value;assert.equal(discovered.datasets.length,25);assert.equal(discovered.nextOffset,25);assert.equal(discovered.selectedFiles.length,16);assert.equal(discovered.nextFileOffset,16);const more=(await ctx.engine.execute({action:'discover',paths,payload:{offset:25,fileOffset:16}})).value;assert.equal(more.datasets.length,1);assert.equal(more.selectedFiles.length,10);assert.equal(more.nextFileOffset,null)}))
test('cross-file unions reject incompatible reviewed row grains',async()=>fixture(async ctx=>{const a=await approve(ctx,await importCsv(ctx,'grain-a.csv','id,value\na,1\n'),{key:['c0'],grain:'One invoice'}),b=await approve(ctx,await importCsv(ctx,'grain-b.csv','id,value\nb,2\n'),{key:['c0'],grain:'One invoice line'});await assert.rejects(()=>ctx.engine.execute({action:'query',paths:[a.path,b.path],payload:{datasetIds:[a.id,b.id],metrics:[{op:'count',as:'n'}]}}),/row grains/)}))
