/** New Explorer copy. Existing editor/settings language dictionaries stay unchanged. */
const en = {
  copy: 'Copy', copyHelp: 'Files copied to Nawa clipboard. Open a destination folder and choose Paste.', itemsCopied: 'items copied.',
  home: 'Home', recent: 'Recent', starred: 'Starred', folders: 'Workspace folders', add: 'Add folder', remove: 'Remove workspace folder',
  back: 'Back', forward: 'Forward', up: 'Up one level', refresh: 'Refresh', search: 'Search this folder', searchFiles: 'Search files', address: 'Folder address',
  new: 'New', newFolder: 'Folder', document: 'Document', spreadsheet: 'Spreadsheet', presentation: 'Presentation', pdf: 'PDF', markdown: 'Markdown', html: 'HTML',
  open: 'Open', openFile: 'Open file', rename: 'Rename', cut: 'Cut', paste: 'Paste', copyPath: 'Copy path', duplicate: 'Duplicate', trash: 'Move to Recycle Bin',
  sort: 'Sort', view: 'View', name: 'Name', modified: 'Date modified', type: 'Type', size: 'Size', ascending: 'Ascending', descending: 'Descending',
  details: 'Details', tiles: 'Large icons', compact: 'Compact spacing', navigation: 'Navigation pane', assistant: 'Nawa assistant', ask: 'Ask about selection',
  folderContext: 'List opened folder', settings: 'Settings', reveal: 'Show in Explorer', close: 'Close', cancel: 'Cancel', save: 'Save', retry: 'Try again',
  loading: 'Loading…', noResults: 'No matching files', noResultsHelp: 'Try a different name or file extension. Search filters the current folder, not its subfolders.',
  empty: 'This folder is empty', emptyHelp: 'No visible files or folders were found here.',
  welcome: 'Your files, with a little intelligence.', welcomeHelp: 'Add a workspace folder to browse documents and ask Nawa about their contents.',
  chooseFolder: 'Choose a folder to start', chooseFolderHelp: 'Open or select a folder to list its items. Select individual files in the main panel to allow reading their contents.',
  selectDetails: 'Select an item to see its details', file: 'File', folder: 'Folder', items: 'items', selected: 'selected', local: 'Local workspace',
  allLoaded: 'All loaded', loadMore: 'Load more', selectedContext: 'Selection context', removeTitle: 'Remove this workspace folder?',
  removeHelp: 'This removes the folder from Nawa only. It does not delete, move, or change any files. Saved folder chats are kept.',
  deleteTitle: 'Move selected items to Recycle Bin?', deleteHelp: 'This changes files on disk. Items can be restored from the operating system Recycle Bin.',
  newFolderTitle: 'Create folder', renameTitle: 'Rename item', nameLabel: 'Name', invalidName: 'Enter a valid Windows file or folder name.',
  notMounted: 'Choose an address inside an added workspace folder. Use Add folder to register another location.',
  copied: 'Path copied to clipboard.', clipboardError: 'Clipboard access failed. You can copy the address from the address bar.',
  moveHelp: 'Items marked for moving. Navigate to a destination folder and choose Paste.', moved: 'Move completed.',
  readOnly: 'AI changes require approval', editor: 'Editor', files: 'Files', backFiles: 'Back to files', selection: 'Selection', path: 'Location',
  totalSize: 'Total file size', unavailable: 'Unavailable', rootsEmpty: 'Add a folder using +', rootTabs: 'Folder workspaces',
  folderScope: 'Chat about selection', clearSearch: 'Clear search', checked: 'Select item', resetLayout: 'Reset layout',
} as const
export type ExplorerString = keyof typeof en
const ja: Record<ExplorerString, string> = {
  copy: 'コピー', copyHelp: 'Nawaのクリップボードにコピーしました。移動先フォルダーで貼り付けてください。', itemsCopied: '件をコピーしました。',
  home:'ホーム',recent:'最近使った項目',starred:'お気に入り',folders:'ワークスペース',add:'フォルダーを追加',remove:'ワークスペースから外す',
  back:'戻る',forward:'進む',up:'上の階層へ',refresh:'更新',search:'このフォルダーを検索',searchFiles:'ファイルを検索',address:'フォルダーのアドレス',
  new:'新規',newFolder:'フォルダー',document:'文書',spreadsheet:'スプレッドシート',presentation:'プレゼンテーション',pdf:'PDF',markdown:'Markdown',html:'HTML',
  open:'開く',openFile:'ファイルを開く',rename:'名前の変更',cut:'切り取り',paste:'貼り付け',copyPath:'パスをコピー',duplicate:'複製',trash:'ごみ箱に移動',
  sort:'並べ替え',view:'表示',name:'名前',modified:'更新日時',type:'種類',size:'サイズ',ascending:'昇順',descending:'降順',
  details:'詳細',tiles:'大きいアイコン',compact:'コンパクト表示',navigation:'ナビゲーション',assistant:'Nawaアシスタント',ask:'選択項目について質問',
  folderContext:'開いたフォルダーの一覧',settings:'設定',reveal:'エクスプローラーで表示',close:'閉じる',cancel:'キャンセル',save:'保存',retry:'再試行',
  loading:'読み込み中…',noResults:'一致するファイルはありません',noResultsHelp:'名前や拡張子を変更してください。検索対象は現在のフォルダー内です。',
  empty:'このフォルダーは空です',emptyHelp:'対応する文書や表示可能なフォルダーが見つかりませんでした。',
  welcome:'ファイル管理を、もっとスマートに。',welcomeHelp:'ワークスペースを追加すると、文書の閲覧や内容についての質問ができます。',
  chooseFolder:'フォルダーを選択してください',chooseFolderHelp:'開いたフォルダーや選択したフォルダーの項目を一覧できます。内容を読むファイルは、メインパネルで個別に選択してください。',
  selectDetails:'項目を選択すると詳細が表示されます',file:'ファイル',folder:'フォルダー',items:'項目',selected:'選択中',local:'ローカルワークスペース',
  allLoaded:'すべて読み込み済み',loadMore:'さらに読み込む',selectedContext:'選択項目のコンテキスト',removeTitle:'このワークスペースを外しますか？',
  removeHelp:'Nawaの登録のみを解除します。フォルダーやファイルは削除・移動されません。チャット履歴も保持されます。',
  deleteTitle:'選択した項目をごみ箱に移動しますか？',deleteHelp:'ディスク上のファイルを移動します。復元するにはOSのごみ箱を使用してください。',
  newFolderTitle:'フォルダーを作成',renameTitle:'名前を変更',nameLabel:'名前',invalidName:'Windowsで使用できるファイル名またはフォルダー名を入力してください。',
  notMounted:'追加済みワークスペース内のアドレスを指定してください。別の場所は「フォルダーを追加」で登録できます。',
  copied:'パスをコピーしました。',clipboardError:'コピーできませんでした。アドレスバーからパスをコピーしてください。',
  moveHelp:'移動先のフォルダーで「貼り付け」を選択してください。',moved:'移動が完了しました。',readOnly:'AIによる変更には承認が必要です',editor:'エディター',files:'ファイル',backFiles:'ファイル一覧に戻る',
  selection:'選択項目',path:'場所',totalSize:'ファイルの合計サイズ',unavailable:'利用できません',rootsEmpty:'＋でフォルダーを追加',rootTabs:'フォルダーワークスペース',
  folderScope:'選択項目についてチャット',clearSearch:'検索をクリア',checked:'項目を選択',resetLayout:'レイアウトをリセット',
}
const ar: Record<ExplorerString, string> = {
  copy: 'نسخ', copyHelp: 'تم نسخ الملفات إلى حافظة نوى. افتح مجلد الوجهة واختر لصق.', itemsCopied: 'عناصر تم نسخها.',
  home:'الرئيسية',recent:'الأخيرة',starred:'المفضلة',folders:'مجلدات مساحة العمل',add:'إضافة مجلد',remove:'إزالة مجلد من مساحة العمل',
  back:'رجوع',forward:'تقدم',up:'المجلد الأعلى',refresh:'تحديث',search:'البحث في هذا المجلد',searchFiles:'البحث في الملفات',address:'عنوان المجلد',
  new:'جديد',newFolder:'مجلد',document:'مستند',spreadsheet:'جدول بيانات',presentation:'عرض تقديمي',pdf:'PDF',markdown:'Markdown',html:'HTML',
  open:'فتح',openFile:'فتح ملف',rename:'إعادة تسمية',cut:'قص',paste:'لصق',copyPath:'نسخ المسار',duplicate:'إنشاء نسخة',trash:'نقل إلى سلة المحذوفات',
  sort:'فرز',view:'عرض',name:'الاسم',modified:'تاريخ التعديل',type:'النوع',size:'الحجم',ascending:'تصاعدي',descending:'تنازلي',
  details:'التفاصيل',tiles:'أيقونات كبيرة',compact:'عرض مضغوط',navigation:'لوحة التنقل',assistant:'مساعد نوى',ask:'اسأل عن التحديد',
  folderContext:'عرض عناصر المجلد المفتوح',settings:'الإعدادات',reveal:'عرض في المستكشف',close:'إغلاق',cancel:'إلغاء',save:'حفظ',retry:'إعادة المحاولة',
  loading:'جارٍ التحميل…',noResults:'لا توجد ملفات مطابقة',noResultsHelp:'جرّب اسماً أو امتداداً آخر. يشمل البحث المجلد الحالي فقط ولا يشمل مجلداته الفرعية.',
  empty:'هذا المجلد فارغ',emptyHelp:'لم يتم العثور على مستندات مدعومة أو مجلدات ظاهرة.',
  welcome:'ملفاتك، بلمسة من الذكاء.',welcomeHelp:'أضف مجلد عمل لتصفح المستندات وسؤال نوى عن محتوياتها.',
  chooseFolder:'اختر مجلداً للبدء',chooseFolderHelp:'افتح مجلداً أو حدده لعرض عناصره. لقراءة محتوى الملفات، حدد كل ملف في اللوحة الرئيسية.',
  selectDetails:'حدد عنصراً لعرض تفاصيله',file:'ملف',folder:'مجلد',items:'عناصر',selected:'محدد',local:'مساحة عمل محلية',
  allLoaded:'تم تحميل الكل',loadMore:'تحميل المزيد',selectedContext:'سياق التحديد',removeTitle:'إزالة مجلد مساحة العمل؟',
  removeHelp:'يُزال تسجيل المجلد من نوى فقط. لن تُحذف الملفات أو تُنقل أو تُعدل، وتُحفظ المحادثات.',
  deleteTitle:'نقل العناصر المحددة إلى سلة المحذوفات؟',deleteHelp:'يغيّر هذا الملفات على القرص. يمكن استعادتها من سلة المحذوفات في نظام التشغيل.',
  newFolderTitle:'إنشاء مجلد',renameTitle:'إعادة تسمية عنصر',nameLabel:'الاسم',invalidName:'أدخل اسماً صالحاً لملف أو مجلد Windows.',
  notMounted:'اختر عنواناً داخل مجلد عمل مضاف. استخدم إضافة مجلد لتسجيل موقع آخر.',
  copied:'تم نسخ المسار.',clipboardError:'تعذر الوصول إلى الحافظة. يمكنك نسخ المسار من شريط العنوان.',
  moveHelp:'انتقل إلى مجلد الوجهة ثم اختر لصق.',moved:'اكتمل النقل.',readOnly:'تغييرات المساعد تتطلب موافقتك',editor:'المحرر',files:'الملفات',backFiles:'العودة إلى الملفات',
  selection:'التحديد',path:'الموقع',totalSize:'إجمالي حجم الملفات',unavailable:'غير متاح',rootsEmpty:'أضف مجلداً باستخدام +',rootTabs:'مساحات عمل المجلدات',
  folderScope:'محادثة حول التحديد',clearSearch:'مسح البحث',checked:'تحديد عنصر',resetLayout:'إعادة ضبط التخطيط',
}
export function explorerText(lang: string): (key: ExplorerString) => string {
  const dictionary = lang === 'ja' ? ja : lang === 'ar' ? ar : en
  return key => dictionary[key]
}
