import { useEffect, useRef, useState } from 'react'
import type { Dataset, TablePolicy, AnalyticsProgress } from '../../../shared/analytics-api'
import './analytics.css'
const failure=(e:unknown)=>e instanceof Error?e.message:String(e)
function ReviewTable({dataset,onSaved}:{dataset:Dataset;onSaved():void}){
  const [policy,setPolicy]=useState<TablePolicy>({...dataset.policy,columns:dataset.policy.columns.map(c=>({...c}))}),[raw,setRaw]=useState(''),[advanced,setAdvanced]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const change=(patch:Partial<TablePolicy>)=>{setPolicy(p=>({...p,...patch}));setConfirmed(false)}
  const save=async()=>{setBusy(true);setError('');try{const next=advanced?JSON.parse(raw) as TablePolicy:policy;await window.nawaAnalytics.review(dataset.id,dataset.generation,{...next,confirmed});onSaved()}catch(e){setError(failure(e))}finally{setBusy(false)}}
  return <div className="nawa-data-review" onKeyDown={e=>e.stopPropagation()}>
    <p><strong>{dataset.name}</strong> · {dataset.sheet||dataset.kind} · {dataset.rawRows.toLocaleString()} imported source records</p>
    <p className="nawa-data-path">{dataset.path}<br/>Source SHA-256: <code>{dataset.sourceHash}</code></p>
    <div className="nawa-data-warnings">{dataset.warnings.map((w,i)=><p key={i}>{w}</p>)}</div>
    <div className="nawa-data-table-scroll"><table><caption>Bounded source preview—not a statistical sample</caption><thead><tr><th>Source row</th>{dataset.policy.columns.slice(0,16).map(c=><th key={c.id}>{c.name}</th>)}</tr></thead><tbody>{dataset.preview.map(row=><tr key={row.row}><th>{row.row}</th>{row.values.slice(0,16).map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div>
    {!advanced&&<>
      <label className="nawa-data-field"><span>What does one row represent? (required)</span><input className="set-input" value={policy.grain} disabled={busy} placeholder="One invoice line, one customer, one sensor observation…" onChange={e=>change({grain:e.target.value})}/></label>
      <label className="nawa-data-field"><span>Table description</span><input className="set-input" value={policy.description} disabled={busy} onChange={e=>change({description:e.target.value})}/></label>
      <div className="nawa-data-settings-grid"><label className="nawa-data-field"><span>First data row</span><input className="set-input" type="number" min={1} disabled={busy} value={policy.firstRow} onChange={e=>change({firstRow:Number(e.target.value)})}/></label><label className="nawa-data-field"><span>Last data row (blank = imported end)</span><input className="set-input" type="number" min={policy.firstRow} disabled={busy} value={policy.lastRow??''} onChange={e=>change({lastRow:e.target.value===''?null:Number(e.target.value)})}/></label></div>
      <label className="nawa-data-field"><span>Unique row key: column IDs separated by commas</span><input className="set-input" disabled={busy} value={policy.key.join(',')} placeholder="c0 or c0,c1; required for combining overlapping-risk exports" onChange={e=>change({key:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label>
      <label className="nawa-data-field"><span>Currency column</span><select className="set-input" disabled={busy} value={policy.currencyColumn??''} onChange={e=>change({currencyColumn:e.target.value||null})}><option value="">None / no mixed-currency measure</option>{policy.columns.map(c=><option key={c.id} value={c.id}>{c.id} · {c.name}</option>)}</select></label>
      <label className="nawa-data-field"><span>Formula handling</span><select className="set-input" disabled={busy} value={policy.formulaPolicy} onChange={e=>change({formulaPolicy:e.target.value as TablePolicy['formulaPolicy']})}><option value="reject">Reject formula cells until resolved</option><option value="saved-cache">Use saved cached values (unverified; no recalculation)</option></select></label>
      <label className="nawa-data-check"><input type="checkbox" checked={policy.includeHiddenRows} disabled={busy} onChange={e=>change({includeHiddenRows:e.target.checked})}/> Include hidden source rows</label>
      <div className="nawa-data-table-scroll"><table><caption>Column types and units apply to every included row; invalid data blocks publication.</caption><thead><tr><th>ID / name</th><th>Type</th><th>Role</th><th>Scale</th><th>Unit</th></tr></thead><tbody>{policy.columns.map((c,i)=><tr key={c.id}><td><code>{c.id}</code> {c.name}</td><td><select disabled={busy} value={c.type} onChange={e=>change({columns:policy.columns.map((x,j)=>j===i?{...x,type:e.target.value as typeof c.type}:x)})}>{['text','integer','decimal','real','date','boolean'].map(t=><option key={t}>{t}</option>)}</select></td><td><select disabled={busy} value={c.role} onChange={e=>change({columns:policy.columns.map((x,j)=>j===i?{...x,role:e.target.value as typeof c.role}:x)})}>{['identifier','dimension','measure'].map(t=><option key={t}>{t}</option>)}</select></td><td><input type="number" min={0} max={12} disabled={busy||c.type!=='decimal'} value={c.scale} onChange={e=>change({columns:policy.columns.map((x,j)=>j===i?{...x,scale:Number(e.target.value)}:x)})}/></td><td><input value={c.unit} disabled={busy} placeholder="JPY, units, percent…" onChange={e=>change({columns:policy.columns.map((x,j)=>j===i?{...x,unit:e.target.value}:x)})}/></td></tr>)}</tbody></table></div>
    </>}
    <button type="button" className="set-btn" disabled={busy} onClick={()=>{if(!advanced)setRaw(JSON.stringify(policy,null,2));else{try{const draft=JSON.parse(raw);if(!draft||typeof draft!=='object'||!Array.isArray(draft.columns)||!draft.columns.length||!Array.isArray(draft.key)||typeof draft.grain!=='string'||!draft.columns.every((c:unknown)=>c&&typeof c==='object'&&'id' in c&&'name' in c&&'type' in c))throw new Error('Policy JSON must retain the table fields, columns and key arrays.');setPolicy(draft as TablePolicy)}catch(e){setError(failure(e));return}}setAdvanced(v=>!v);setConfirmed(false)}}>{advanced?'Use form':'Advanced policy JSON: column ranges, skipRows, descriptions and nullability'}</button>
    {advanced&&<label className="nawa-data-field"><span>Reviewed table policy JSON</span><textarea spellCheck={false} className="nawa-data-json" value={raw} disabled={busy} rows={20} onChange={e=>{setRaw(e.target.value);setConfirmed(false)}}/></label>}
    <label className="nawa-data-check"><input type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I confirm the intended row grain, range, column types, units, exclusions and formula policy. This validates local analytical tables; it does not change the source workbook.</label>
    <button type="button" className="set-btn primary" disabled={busy||!confirmed} onClick={()=>void save()}>{busy?'Validating all included rows…':'Validate and approve table'}</button>
    {error&&<p role="alert" className="nawa-data-error">{error}</p>}
  </div>
}
export function AnalyticsToolbar({folder, inSidebar = false }:{folder:string|null; inSidebar?: boolean }){
  const [recursive,setRecursive]=useState(false),[consent,setConsent]=useState(false),[progress,setProgress]=useState<AnalyticsProgress|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[open,setOpen]=useState(false),[datasets,setDatasets]=useState<Dataset[]>([]),[reviewId,setReviewId]=useState<string|null>(null),[clear,setClear]=useState(false),[nextOffset,setNextOffset]=useState<number|null>(null)
  const epoch=useRef(0),alive=useRef(true)
  const folderRef=useRef(folder);folderRef.current=folder
  useEffect(()=>{alive.current=true;epoch.current++;setDatasets([]);setNextOffset(null);setReviewId(null);setConsent(false);setClear(false);setError('');setNotice('');setBusy(false);const token=epoch.current
    if(!window.nawaAnalytics){setError('Structured data bridge unavailable. Rebuild and restart Nawa.');return}
    let pending=false
    const poll=()=>{if(pending)return;pending=true;void window.nawaAnalytics.progress().then(p=>{if(alive.current&&epoch.current===token)setProgress(p)}).catch(e=>{if(alive.current&&epoch.current===token)setError(failure(e))}).finally(()=>{pending=false})}
    poll();const off=window.nawaAnalytics.onChanged(poll),timer=setInterval(poll,1500)
    return()=>{alive.current=false;off();clearInterval(timer)}
  },[folder])
  const load=async(offset=0)=>{if(!folder||folderRef.current!==folder)return;const requested=folder,token=epoch.current;const catalog=await window.nawaAnalytics.catalog(folder,offset);if(alive.current&&token===epoch.current&&folderRef.current===requested){setDatasets(old=>offset?[...new Map([...old,...catalog.datasets].map(d=>[d.id,d])).values()]:catalog.datasets);setNextOffset(catalog.nextOffset);setNotice(`${catalog.total} imported tables in this directory scope. Use Load more tables to continue reviewing a large workbook.`)}}
  const perform=async(work:()=>Promise<unknown>)=>{if(busy)return;const token=epoch.current;setBusy(true);setError('');try{await work()}catch(e){if(alive.current&&token===epoch.current)setError(failure(e))}finally{if(alive.current&&token===epoch.current)setBusy(false)}}
  if(!folder)return null
  const running=progress?.running===true
  return <section className="nawa-data-toolbar" aria-label="Structured data analysis" onContextMenu={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}>
    <details open={inSidebar || (open)} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Structured Data Analysis · SQL + statistics + RAG context</summary>
      <p>Import complete table records into local SQLite. No embedding server is needed for analysis. The assistant can query only individually selected files whose tables have been reviewed.</p>
      <label className="nawa-data-check"><input type="checkbox" disabled={busy||running} checked={recursive} onChange={e=>setRecursive(e.target.checked)}/> Include subdirectories</label>
      <label className="nawa-data-check"><input type="checkbox" disabled={busy||running} checked={consent} onChange={e=>setConsent(e.target.checked)}/> I allow local saved-file snapshots, raw records, approved tables and result receipts to be stored unencrypted in Nawa’s separate analytical database.</label>
      <div className="nawa-data-actions"><button type="button" className="set-btn primary" disabled={busy||running||!consent} onClick={()=>void perform(async()=>{await window.nawaAnalytics.importFolder(folder,recursive,consent);await load()})}>Import / refresh table data</button><button type="button" className="set-btn" disabled={busy||running} onClick={()=>void perform(load)}>Review imported tables</button><button type="button" className="set-btn" disabled={busy||running} onClick={()=>setClear(true)}>Clear analytical data</button></div>
      {clear&&<div role="group" aria-label="Confirm clearing analytical data"><p>Remove analytical records and related result receipts for this folder and its subdirectories? Source files, chats and RAG embeddings are not deleted.</p><button type="button" className="set-btn danger" disabled={busy||running} onClick={()=>void perform(async()=>{await window.nawaAnalytics.clear(folder);if(folderRef.current!==folder)return;setClear(false);setDatasets([]);setNextOffset(null);setReviewId(null)})}>Clear this directory’s analytical records</button> <button type="button" className="set-btn" onClick={()=>setClear(false)}>Keep data</button></div>}
      {notice&&<p role="status">{notice}</p>}
      <div className="nawa-data-catalog">{datasets.map(d=><article key={`${d.id}:${d.generation}`}><div className="nawa-data-catalog-heading"><span><strong>{d.name}</strong> · {d.sheet||d.kind} · {d.status==='ready'?`${d.rows.toLocaleString()} approved rows`:'Needs review'}</span><button type="button" className="set-btn" disabled={busy||running} onClick={()=>setReviewId(reviewId===d.id?null:d.id)}>{reviewId===d.id?'Close review':'Review policy'}</button></div>{reviewId===d.id&&<ReviewTable dataset={d} onSaved={()=>{if(folderRef.current!==folder)return;setReviewId(null);void perform(load)}}/>}</article>)}</div>
      {nextOffset!==null&&<button type="button" className="set-btn" disabled={busy||running} onClick={()=>void perform(()=>load(nextOffset!))}>Load more tables</button>}
    </details>
    {running&&<div className="nawa-data-running"><span role="status">{progress?.message} · {progress?.scanned} files checked · {progress?.rows.toLocaleString()} records read</span><button type="button" className="set-btn" onClick={()=>{void window.nawaAnalytics.cancel().catch(e=>setError(failure(e)))}}>Stop data operation</button></div>}
    {!running&&progress?.folder===folder&&progress?.message&&<p role="status">{progress.message}</p>}
    {error&&<p className="nawa-data-error" role="alert">{error}</p>}
  </section>
}
