import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import {pathToFileURL} from 'node:url'
import {createRequire} from 'node:module'
import {transformSources,transformExplorer,transformToolbar,transformPreferences,validateExplorer,SOURCE_PATHS} from './transform.mjs'
import {sourcesFixture,explorerFixture,toolbarFixture,assistantExpression} from './fixtures.mjs'
const root=process.env.NAWA_INSPECTOR_PROJECT,build=process.env.NAWA_INSPECTOR_BUILD
if(!root||!build)throw new Error('Run through tools/inspector-tabs/test.mjs.')
const ts=createRequire(path.join(root,'package.json'))('typescript')
const {WorkspaceInspector,PreservedInspectorPanel}=await import(pathToFileURL(path.join(build,'WorkspaceInspector.mjs')).href)
const hooks=await import(pathToFileURL(path.join(build,'hooks.mjs')).href)
const {INSPECTOR_TABS,nextInspectorTab,isInspectorTab}=await import(pathToFileURL(path.join(build,'inspector-tabs-model.mjs')).href)
const {parsePreferences}=await import(pathToFileURL(path.join(build,'preferences.mjs')).href)
const text=node=>typeof node==='string'?node:typeof node==='number'?String(node):node&&typeof node==='object'?(node.children||[]).map(text).join(' '):''
const all=node=>node&&typeof node==='object'?[node,...(node.children||[]).flatMap(all)]:[]
function render(active='ai',extras={}){hooks.begin('inspector-'+active);return WorkspaceInspector({active,assistantLabel:'Nawa assistant',detailsLabel:'Details',closeLabel:'Close panel',folder:'C:\\Data',assistant:'conversation',details:'metadata',rag:'rag-controls',analytics:'table-review',onChange:()=>{},onClose:()=>{},onAddFolder:()=>{},...extras})}
test('moves both original toolbar instances into sidebar without duplicating them',()=>{const result=transformSources(ts,sourcesFixture());validateExplorer(ts,result.get(SOURCE_PATHS[0]));assert.match(result.get(SOURCE_PATHS[0]),/rag=\{<RagToolbar/);assert.match(result.get(SOURCE_PATHS[0]),/analytics=\{<AnalyticsToolbar/)})
test('ignores unrelated inspectorVisible expressions and targets the actual inspector host',()=>{const result=transformExplorer(ts,explorerFixture());assert.match(result,/unrelated-visibility-one/);assert.match(result,/unrelated-visibility-two/);assert.equal((result.match(/<WorkspaceInspector/g)||[]).length,1)})
test('supports the prior UI/status hotfix layout and removes its global shortcut row',()=>{const result=transformSources(ts,sourcesFixture(true)).get(SOURCE_PATHS[0]);assert.doesNotMatch(result,/IndexingShortcuts/);assert.doesNotMatch(result,/nawa-indexing-panels/);assert.match(result,/onSettings=\{\(\) => openIndexingSettings\('rag'\)/)})
test('retains the original chat selection, folder, callbacks and empty-state expression verbatim',()=>{const result=transformExplorer(ts,explorerFixture());assert.ok(result.includes('assistant={'+assistantExpression+'}'))})
test('retains existing pane-resize and close behavior',()=>{const result=transformExplorer(ts,explorerFixture());assert.match(result,/value=\{effectiveInspectorWidth\}/);assert.match(result,/reverse onChange=\{inspectorWidth => changePrefs\(\{ inspectorWidth \}\)\}/);assert.match(result,/onClose=\{\(\) => changePrefs\(\{ pane: 'none' \}\)\}/)})
test('adds direct entries in View without altering existing assistant/details entries',()=>{const result=transformExplorer(ts,explorerFixture());assert.match(result,/label: 'Directory RAG'/);assert.match(result,/label: 'Structured Data Analysis'/);assert.match(result,/label: t\('assistant'\)/)})
test('sidebar toolbar disclosures remain open while consent stays required',()=>{for(const name of ['RagToolbar','AnalyticsToolbar']){const result=transformToolbar(ts,toolbarFixture(name),name);assert.match(result,/inSidebar\?: boolean/);assert.match(result,/open=\{inSidebar \|\|/);assert.match(result,/disabled=\{!consent\}/)}})
test('toolbar settings/add-folder callbacks from the hotfix remain present',()=>{const result=transformToolbar(ts,toolbarFixture('RagToolbar',true),'RagToolbar');assert.match(result,/onSettings/);assert.match(result,/onAddFolder/);assert.match(result,/inSidebar/)} )
test('applying the complete source transform twice is idempotent',()=>{for(const variant of [false,true]){const first=transformSources(ts,sourcesFixture(variant)),second=transformSources(ts,first);assert.deepEqual(second,first)}})
test('preserves unrelated edits, UTF-8 BOM and CRLF line endings',()=>{const source=sourcesFixture(true);for(const [p,s]of source)source.set(p,'\uFEFF'+s.replace(/\n/g,'\r\n'));const out=transformSources(ts,source);for(const [p,s]of out){assert.ok(s.startsWith('\uFEFF'));assert.equal(s.replace(/\r\n/g,'').includes('\n'),false);if(p.endsWith('ExplorerHome.tsx'))assert.match(s,/LOCAL EDIT MUST SURVIVE/)}})
test('refuses duplicate toolbar placement rather than moving the wrong instance',()=>assert.throws(()=>transformExplorer(ts,explorerFixture().replace('<FileList items={items} />','<FileList items={items}/><RagToolbar folder={folder}/>')),/expected one source node/))
test('refuses to remove unrelated content from an existing panels wrapper',()=>assert.throws(()=>transformExplorer(ts,explorerFixture(true).replace('<div className="nawa-indexing-panels">','<div className="nawa-indexing-panels"><p>Custom content</p>')),/unrelated content/))
test('rejects incomplete or malformed source before mutation',()=>{assert.throws(()=>transformExplorer(ts,'export function ExplorerHome(){return <'));assert.throws(()=>transformSources(ts,new Map()),/missing/)})
test('retains all old panel preferences and restores both new tabs',()=>{for(const pane of ['ai','details','rag','analytics','none'])assert.equal(parsePreferences(JSON.stringify({pane})).pane,pane)})
test('unknown panel preferences fall back safely',()=>{assert.equal(parsePreferences('{"pane":"unknown"}').pane,'ai');assert.equal(parsePreferences('invalid').pane,'ai')})
test('four tab labels are visible and retain exact feature names',()=>{const tree=render();const tabs=all(tree).filter(n=>n.props.role==='tab');assert.equal(tabs.length,4);assert.deepEqual(tabs.map(text),[' Nawa assistant',' Details',' Directory RAG',' Structured Data Analysis']);assert.deepEqual(INSPECTOR_TABS,['ai','details','rag','analytics'])})
test('one tab is selected and one is in the sequential keyboard focus order',()=>{const tabs=all(render('rag')).filter(n=>n.props.role==='tab');assert.equal(tabs.filter(n=>n.props['aria-selected']).length,1);assert.equal(tabs.filter(n=>n.props.tabIndex===0).length,1)})
test('tab buttons point to stable panel IDs with distinct labels',()=>{const tree=render('analytics'),tabs=all(tree).filter(n=>n.props.role==='tab'),panels=all(tree).filter(n=>n.type===PreservedInspectorPanel);assert.equal(new Set(tabs.map(n=>n.props.id)).size,4);for(let i=0;i<4;i++){assert.equal(tabs[i].props['aria-controls'],panels[i].props.id);assert.equal(panels[i].props.labelledBy,tabs[i].props.id)}})
test('clicking feature tabs selects the pane without invoking a file operation',()=>{const calls=[],tree=render('ai',{onChange:tab=>calls.push(tab)});for(const n of all(tree).filter(n=>n.props.role==='tab'))n.props.onClick();assert.deepEqual(calls,['ai','details','rag','analytics'])})
test('close control is separate from tab keyboard navigation',()=>{let closed=false;const tree=render('ai',{onClose:()=>closed=true});const button=all(tree).find(n=>n.type==='button'&&n.props['aria-label']==='Close panel');assert.ok(button);assert.equal(button.props.role,undefined);button.props.onClick();assert.equal(closed,true)})
test('initially inactive panels do not mount history or table-review children',()=>{hooks.begin('unvisited');const child={sensitive:true};const panel=PreservedInspectorPanel({active:false,name:'ai',id:'a',labelledBy:'t',children:child});assert.equal(panel.props.hidden,true);assert.equal(panel.children.includes(child),false)})
test('visited assistant remains mounted when switching to other tabs',()=>{const child={conversation:'same instance'};hooks.begin('retained');const first=PreservedInspectorPanel({active:true,name:'ai',id:'a',labelledBy:'t',children:child});hooks.begin('retained');const hidden=PreservedInspectorPanel({active:false,name:'ai',id:'a',labelledBy:'t',children:child});assert.equal(first.children[0],child);assert.equal(hidden.children[0],child);assert.equal(hidden.props.hidden,true);assert.equal(hidden.props.tabIndex,-1)})
test('rapid first activation then hide retains the form instead of resetting it',()=>{const child={form:'draft'};hooks.begin('fast');PreservedInspectorPanel({active:false,name:'analytics',id:'a',labelledBy:'t',children:child});hooks.begin('fast');PreservedInspectorPanel({active:true,name:'analytics',id:'a',labelledBy:'t',children:child});hooks.begin('fast');const panel=PreservedInspectorPanel({active:false,name:'analytics',id:'a',labelledBy:'t',children:child});assert.equal(panel.children[0],child)})
test('a hidden visited panel receives new scope props rather than frozen old children',()=>{hooks.begin('scope');PreservedInspectorPanel({active:true,name:'ai',id:'a',labelledBy:'t',children:'old selection'});hooks.begin('scope');const panel=PreservedInspectorPanel({active:false,name:'ai',id:'a',labelledBy:'t',children:'new selection'});assert.equal(panel.children[0],'new selection')})
test('unopened-directory tabs explain the required folder scope',()=>{const tree=render('rag',{folder:null});const panels=all(tree).filter(n=>n.type===PreservedInspectorPanel);assert.match(text(panels[2]),/Open a directory/);assert.match(text(panels[3]),/Add \/ open folder/)})
test('keyboard navigation handles wrapping, grid movement and RTL',()=>{assert.equal(nextInspectorTab('analytics','ArrowRight'),'ai');assert.equal(nextInspectorTab('ai','ArrowLeft'),'analytics');assert.equal(nextInspectorTab('ai','ArrowDown'),'rag');assert.equal(nextInspectorTab('rag','ArrowUp'),'ai');assert.equal(nextInspectorTab('ai','ArrowRight',true),'analytics');assert.equal(nextInspectorTab('rag','Home'),'ai');assert.equal(nextInspectorTab('ai','End'),'analytics');assert.equal(nextInspectorTab('ai','Enter'),null);assert.equal(isInspectorTab('none'),false)})
test('CSS hides inactive panels and gives table review its own scrollable sidebar',async()=>{const css=await fs.readFile(path.join(root,'apps/shell/src/renderer/src/explorer/workspace-inspector.css'),'utf8');assert.match(css,/\[hidden\][^{]*\{\s*display:none !important/);assert.match(css,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.match(css,/nawa-data-table-scroll/);assert.match(css,/max-height:none/);assert.match(css,/is-ai > \.workspace-chat-main/)} )

test('refuses to discard unrelated widgets added to the existing inspector',()=>assert.throws(()=>transformExplorer(ts,explorerFixture().replace('</aside></>}', '<p>Custom inspector widget</p></aside></>}')),/additional content/))
